apiVersion: v1
clusters:
  - cluster:
      certificate-authority: C:\Users\Karthik Patil\.minikube\ca.crt
      extensions:
        - extension:
            last-update: Thu, 27 Nov 2025 10:39:49 IST
            provider: minikube.sigs.k8s.io
            version: v1.34.0
          name: cluster_info
      server: https://127.0.0.1:60993
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 27 Nov 2025 10:39:49 IST
            provider: minikube.sigs.k8s.io
            version: v1.34.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: C:\Users\Karthik Patil\.minikube\profiles\minikube\client.crt
      client-key: C:\Users\Karthik Patil\.minikube\profiles\minikube\client.key
